# Generated by Django 4.2.30 on 2026-06-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpaper',
            name='output_language',
            field=models.CharField(default='English (US)', max_length=50),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='summary_size',
            field=models.CharField(default='medium', max_length=50),
        ),
    ]
